### PR TITLE
Use run_started_at instead of created_at

### PR DESCRIPTION
**Pull request by joreetz-otto**
This will fix a problem where a 're-run' will start even if there is a newer run started

### CODE REVIEW

**Comment by ahmadnassri** [comment]
I'll fix the lint issues and merge manually ... thank you!

**Comment by joreetz-otto** [comment]
Thanks for the fast response, should I close this or will you do it?

**Comment by ahmadnassri** [comment]
I'll take care of it, just making sure it releases properly

**Comment by ahmadnassri** [comment]
been waiting on a github actions issues ... still waiting for them to be fixed ... at least they are now acknowledging it on https://status.github.com

**Comment by ahmadnassri** [comment]
it's now released in v1.1.1

**Pull request closed without merging**
